FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /bin/migrate ./cmd/migrate

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /bin/migrate /bin/migrate
COPY db/migrations ./db/migrations

ENTRYPOINT ["/bin/migrate"]
